# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-backup
  description: Terraform module to provision AWS Backup, a fully managed backup service that makes it easy to centralize and automate the back up of data across AWS services such as EBS volumes, RDS databases, DynamoDB tables, EFS file systems, and AWS Storage Gateway volumes.
  homepage: https://cloudposse.com/accelerate
  topics: hcl2, aws, terraform, terraform-modules, terraform-module, backup, backups, aws-dynamodb, aws-efs, efs, efs-backup, efs-volume, dynamodb, dynamodb-backup, rds, rds-database, rds-backup, ebs, ebs-backup, ebs-volumes



